name: Pasty

options:
  bundleIdPrefix: com.pasty
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.2"
  minimumXcodeVersion: "16.2"

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.0.0"
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: "5.0.0"
  CocoaLumberjack:
    url: https://github.com/CocoaLumberjack/CocoaLumberjack.git
    from: "3.8.0"

settings:
  base:
    CLANG_CXX_LANGUAGE_STANDARD: c++17
    CLANG_CXX_LIBRARY: libc++
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    SWIFT_VERSION: "5.9"

targets:
  PastyCore:
    type: library.static
    platform: macOS
    sources:
      - path: ../../core/src
        excludes:
          - "**/*.h"
          - "module.modulemap"
          - "thirdparty/**"
        compilerFlags:
          - -Wall
      - path: ../../core/src
        includes:
          - "**/*.h"
          - "module.modulemap"
        buildPhase: none
      - path: ../../core/include/pasty
        excludes:
          - "api/**"
          - "common/**"
        buildPhase: headers
        headerVisibility: public
      - path: ../../core/migrations
        buildPhase: none
    settings:
      HEADER_SEARCH_PATHS:
        - $(SRCROOT)/../../core/include
        - $(SRCROOT)/../../core/src
        - $(SRCROOT)/../../core/src/thirdparty
        - /opt/homebrew/include
        - /usr/local/include
      PRODUCT_NAME: PastyCore
      SKIP_INSTALL: YES
      DEFINES_MODULE: YES
      MODULEMAP_FILE: $(SRCROOT)/../../core/include/pasty/module.modulemap
    dependencies:
      - sdk: libsqlite3.tbd

  Pasty:
    type: application
    platform: macOS
    sources:
      # - path: Sources/App.swift
      # - path: Sources/DesignSystem
      # - path: Sources/Features
      # - path: Sources/Services
      # - path: Sources/Utilities
      - path: Sources
      - path: Info.plist
        buildPhase: none
      - path: Resources/Assets.xcassets
      - path: ../../core/migrations
        buildPhase: resources
        type: folder
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_OBJC_INTEROP_MODE: objcxx
        SWIFT_EMIT_LOC_STRINGS: NO
        LIBRARY_SEARCH_PATHS:
          - $(inherited)
          - /opt/homebrew/lib
          - /usr/local/lib
        OTHER_LDFLAGS:
          - $(inherited)
          - -lsodium
        OTHER_SWIFT_FLAGS:
          - -cxx-interoperability-mode=default
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.pasty.app.debug
          PRODUCT_NAME: PastyDebug
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: com.pasty.app
          PRODUCT_NAME: Pasty
    dependencies:
      - target: PastyCore
      - sdk: Cocoa.framework
      - sdk: libsqlite3.tbd
      - package: KeyboardShortcuts
      - package: SnapKit
      - package: CocoaLumberjack
        product: CocoaLumberjackSwift
