name: Pasty2

options:
  bundleIdPrefix: com.pasty2
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "14.0"

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.0.0"
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: "5.0.0"

settings:
  base:
    CLANG_CXX_LANGUAGE_STANDARD: c++17
    CLANG_CXX_LIBRARY: libc++
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    SWIFT_VERSION: "5.9"

targets:
  PastyCore:
    type: library.static
    platform: macOS
    sources:
      - path: ../../core/src/Pasty.cpp
        compilerFlags:
          - -Wall
      - path: ../../core/src/history
        compilerFlags:
          - -Wall
      - path: ../../core/include/pasty
        buildPhase: headers
        headerVisibility: public
    settings:
      HEADER_SEARCH_PATHS:
        - $(SRCROOT)/../../core/include
      PRODUCT_NAME: PastyCore
      SKIP_INSTALL: YES
      DEFINES_MODULE: YES
      MODULEMAP_FILE: $(SRCROOT)/../../core/include/module.modulemap
    dependencies:
      - sdk: libsqlite3.tbd

  Pasty2:
    type: application
    platform: macOS
    sources:
      - path: Sources
      - path: Info.plist
        buildPhase: none
      - path: ../../core/migrations/0001-initial-schema.sql
        buildPhase: resources
      - path: ../../core/migrations/0002-add-search-index.sql
        buildPhase: resources
      - path: ../../core/migrations/0003-add-metadata.sql
        buildPhase: resources
      - path: ../../core/migrations/0004-add-ocr-support.sql
        buildPhase: resources
    settings:
      INFOPLIST_FILE: Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.pasty2.app
      PRODUCT_NAME: Pasty2
      CODE_SIGN_IDENTITY: "-"
      CODE_SIGNING_REQUIRED: NO
      SWIFT_OBJC_INTEROP_MODE: objcxx
      SWIFT_EMIT_LOC_STRINGS: NO
      OTHER_SWIFT_FLAGS:
        - -cxx-interoperability-mode=default
      HEADER_SEARCH_PATHS:
        - $(SRCROOT)/../../core/include
      SWIFT_INCLUDE_PATHS:
        - $(SRCROOT)/../../core/include
    dependencies:
      - target: PastyCore
      - sdk: Cocoa.framework
      - sdk: libsqlite3.tbd
      - package: KeyboardShortcuts
      - package: SnapKit
